services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volumne:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready","-U","airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: always

volumes:
  pg_data:

